version: "3"

services:
  dnscrypt:
    container_name: DNSCrypt
    image: klutchell/dnscrypt-proxy:latest
    networks:
      pihole_net:
        ipv4_address: 10.0.1.2
    expose:
      - "5300/udp"
      - "5300/tcp"
    environment:
      TZ: 'Europe/Madrid'
    volumes:
      - '~/docker/piholeproxy/dnscrypt-proxy:/config'
    dns:
      - 1.1.1.1
    restart: always

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    networks:
      pihole_net:
        ipv4_address: 10.0.1.3
    ports:
      - "5054:5054/tcp"
      - "5054:5054/udp"
    environment:
        DNS1: 1.1.1.1
        DNS2: 1.0.0.1
        PORT: 5054
        ADDRESS: 0.0.0.0
    restart: always

  pihole:
    container_name: Pi-hole
    image: pihole/pihole:latest
    networks:
      pihole_net:
        ipv4_address: 10.0.1.4
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "83:80/tcp"
      - "446:443/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'lordpedal'
      DNS1: "10.0.1.3#5054"
      DNS2: "10.0.1.2#5300"
      DNSMASQ_LISTENING: 'local'
    volumes:
       - '~/docker/piholeproxy/pihole/:/etc/pihole/'
       - '~/docker/piholeproxy/dnsmasq/:/etc/dnsmasq.d/'
    dns:
      - 1.1.1.1
    restart: always
    depends_on:
      - dnscrypt

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
